version: '3.8'
services:
  python-env:
    container_name: python_env
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements_python-env.txt && /bin/bash"
    stdin_open: true
    tty: true

  flask-app:
    container_name: flask_app
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: bash -c "pip install -r requirements_flask-app.txt && /bin/bash"
    stdin_open: true
    tty: true

  fastapi-app:
    container_name: fastapi_app
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements_fastapi-app.txt && /bin/bash"
    stdin_open: true
    tty: true

  jupyter-notebook:
    container_name: jupyter_notebook
    image: jupyter/base-notebook:python-3.8.6
    volumes:
       - .:/app
    working_dir: /app
    ports:
      - "8888:8888"
    command: bash -c "pip install -r requirements_jupyter-notebook.txt && /bin/bash"
    stdin_open: true
    tty: true

  jupyter-note-r:
    container_name: jupyter_n
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/home/vmendez/work
    ports:
      - "8888:8888"
    command: bash -c "pip install -r requirements_jupyter-notebook.txt && /bin/bash"
    stdin_open: true
    tty: true