version: '3.8'
services:
  python-env:
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash
    stdin_open: true
    tty: true

  flask-app:
    image: python:3.8-slim
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: /bin/bash
    stdin_open: true
    tty: true
